spring:
  application:
    name: zuul
  profiles:
    active: local
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 4000

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

logging:
  level:
    com.netflix.zuul: debug
    #org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices: DEBUG
    #org.springframework.security.web: DEBUG
    #org.springframework.security: DEBUG

---
spring:
  profiles: local

zuul:
  routes:
    service-a:
      path: /service/a/**
      serviceId: service-a
      stripPrefix: false
      url: http://localhost:8080
    service-b:
      path: /service/b/**
      serviceId: service-b
      stripPrefix: false
      url: http://localhost:8081
    auth:
      path: /auth/**
      serviceId: auth
      stripPrefix: true
      url: http://localhost:8082

---
spring:
  profiles: docker

zuul:
  routes:
    service-a:
      path: /service/a/**
      serviceId: service-a
      stripPrefix: false
      url: http://servicea:8080
    service-b:
      path: /service/b/**
      serviceId: service-b
      stripPrefix: false
      url: http://serviceb:8081
    auth:
      path: /auth/**
      serviceId: auth
      stripPrefix: true
      url: http://auth:8082
