logging:
  level:
    com.netflix.zuul: debug
    #org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices: DEBUG
    #org.springframework.security.web: DEBUG
    #org.springframework.security: DEBUG